[package]
name = "rust-wind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
rppal = "0.17.1"
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "macros", "signal"] }
tracing = "0.1.40"
warp = "0.3"
