name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: "sqlite:./db.sqlite"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install sqlite3
      run: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev
    - name: Setup SQLite Database
      run: |
        touch db.sqlite
        sqlite3 db.sqlite "CREATE TABLE IF NOT EXISTS wind (ts REAL PRIMARY KEY, vel  REAL, direction  INTEGER)"


    - name: Lint
      run: 
      run: cargo clippy -- --allow dead_code --allow clippy::missing_errors_doc
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
